### PR TITLE
Fix 1197

### PR DESCRIPTION
**Pull request by rpspringuel**
Mostly some clean-ups that I'd made while working on my other changes (which are, by and large, unnecessary now).

### CODE REVIEW

**Comment by rpspringuel** [comment]
Oh, I forgot to check out the system-setup scripts.  It's time for mass, but I'll work on that in a couple of hours.

**Comment by rpspringuel** [comment]
> Is this rename reflected in CommandIndex_internal.tex?

I forgot that too.  I'll get that in a bit.

**Comment by rpspringuel** [comment]
The documentation change is up.

I have a working modification for `system-setup.command`, but haven't done `system-setup.bat` yet.  Unfortunately I'll be out for the rest of the day so I won't get to that until tomorrow (Monday) at the earliest.  If you want I can submit a separte PR against the main repository for that change at a later date.

**Comment by henryso** [comment]
Ok, sounds like a plan.

**Pull request merged**
